### PR TITLE
zstandard-compare-stream: Ignore error.DictionaryIdFlagUnsupported

### PR DESCRIPTION
**Pull request by dweiller**

### CODE REVIEW

**Comment by squeek502** [comment]
Unless I'm missing something, this not a possible error in `ZstandardStream.Error`.

```
$ zig build fuzz-zstandard-compare-stream
fuzzers/zstandard-compare-stream.zig:77:13: error: expected type '@typeInfo(@typeInfo(@TypeOf(zstandard-compare-stream.zigZstdStreaming)).Fn.return_type.?).ErrorUnion.error_set', found 'error{DictionaryIdFlagUnsupported}'
            error.DictionaryIdFlagUnsupported => return,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fuzzers/zstandard-compare-stream.zig:77:13: note: 'error.DictionaryIdFlagUnsupported' not a member of destination error set
```

**Comment by dweiller** [comment]
It is - there were several cases of this in the last fuzzing set. ~`ZstandardStream.read()` calls `ZstandardStream.frameInit()`, and passes on this error which can be generated [here](https://github.com/ziglang/zig/pull/14394/files#diff-5a707a0754c693ef67162a2fb7c7c0f3b27fcc2eb39ce303c61fcb528b588417R68)~. Hmm, acutally not sure what the code path is right now, but it was definitely in the last fuzzing set. Maybe I need to double check. Maybe there's a mismatch in commits, maybe I removed the error in a later commit than was used by the fuzzer for that run.

**Comment by squeek502** [comment]
Could be something weird going on with the error return trace (or it's being misinterpreted?), as the relevant `ZstandardStream` error set has never included `DictionaryIdFlagUnsupported`. The error would need to be part of the error set here:

https://github.com/dweiller/zig/blob/e4fcce269867964d1bc0a9421e7d9796b460d5b9/lib/std/compress/zstandard.zig#L32-L37

to be possible during this `catch`.

**Comment by squeek502** [comment]
My guess is that the format of the output is being misleading. The real error that got returned is only printed in the 

```
zstd error: error.NoError, zig error: error.MalformedFrame
```

line, but it gets printed after the error return trace, so it's a bit weird. The top of the error return trace may not be the final error that reaches this `catch`, as it prints starting from the place the original error got returned (in this case `DictionaryIdFlagUnsupported` that gets eventually gets translated to `MalformedFrame` I'd assume).

**Comment by dweiller** [comment]
> Could be something weird going on with the error return trace (or it's being misinterpreted?), as the relevant `ZstandardStream` error set has never included `DictionaryIdFlagUnsupported`. The error would need to be part of the error set here:

I just found this too.

I tracked down the issue - the problem is that `ZstandardStream.read()` is masking the error, it shouldn't be doing that. So I guess the next commit in the Zstandard PR is going to require this one be implemented as well.

Edit:
> My guess is that the format of the output is being misleading. The real error that got returned is only printed in the
> 
> ```
> zstd error: error.NoError, zig error: error.MalformedFrame
> ```
> 
> line, but it gets printed after the error return trace, so it's a bit weird. The top of the error return trace may not be the final error that reaches this `catch`, as it prints starting from the place the original error got returned (in this case `DictionaryIdFlagUnsupported` that gets eventually gets translated to `MalformedFrame` I'd assume).

Yep. Asynchronous debugging at it's finest :P

**Comment by squeek502** [comment]
Thanks! The switch was also missing `error.MalformedBlock` and `error.StreamTooLong`, so I added those in.

**Pull request merged**
