### PR TITLE
Add a couple non-std fuzzers

### LINKED ISSUE #8: Fuzzing outside the standard library?
Thanks for creating this project, it's pretty cool to see how many issues can be found with this approach that might not easily be discovered otherwise.

One of my long overdue self-TODOs has been to get fuzzing set up for some of my Zig contributions, which might help find more issues like [this one](https://github.com/ziglang/zig/pull/19577#discussion_r1555161741). However, this code is outside the standard library.

I've taken the approach of accepting a `zig-src` build option to point to a Zig source checkout and used that to add some basic fuzzers for Markdown parsing and Git packfile indexing: https://github.com/ianprime0509/zig-std-lib-fuzzing/tree/non-std-fuzzers I haven't run them for very long yet, but I'm hoping to run them more to see if I can find any other interesting bugs.

Although the declared scope of this project is the Zig standard library, would fuzzers for other stuff in the Zig project be a useful addition?

### PR DESCRIPTION
**Pull request by ianprime0509**
Closes #8

This PR adds two fuzzers for functionality outside the standard library: the Autodoc Markdown parser, and the Git package fetching support (specifically, just the index-pack operation for now). These are dependent on a new `zig-src` build option to give the path to a Zig source tree where the necessary files can be found.

### CODE REVIEW

**Comment by squeek502** [comment]
Looking good, thanks!

Two comments, not necessarily blocking:

- It's typically better to use small inputs; might be worth using a more minimal `.pack` file as the input for the git fuzzer (AFL++ warns about large inputs on startup, not sure if `testrepo.pack` is big enough to trigger that)
- Would be nice to be able to avoid hitting the file system in the git fuzzer if possible. Would obviously require some API changes in the git code, but it'd likely provide a nice iterations/sec improvement during fuzzing.

**Comment by ianprime0509** [comment]
Thanks! Those are good suggestions, I'll take a shot at applying those tomorrow.

You're right that avoiding the filesystem for the Git unpack operation should be pretty easy to do; in my earliest version of that code I had used `anytype` to support a fixed buffer stream, but replaced it with a concrete type in the final version since no other implementations were needed. So it should work fine if I just change it back to `anytype`; I guess the easiest way to do that would just be to copy the file (with a note of where it came from) and make the change here.

**Comment by ianprime0509** [comment]
It took a little longer than I had hoped to come back to this, but I updated the Git test repository to be a smaller, much more minimal example (it just has one commit with two files in it), and I also removed the need for I/O in the Git fuzzer via a patch to upstream `git.zig` to use `anytype` for the packfile input so a `FixedBufferStream` can be used in place of a file.

I was hesitant to duplicate the entire upstream `git.zig` file directly (since it would create a higher ongoing maintenance burden), so I instead opted to just add a patch with the changes needed and apply the patch as part of the Git fuzzer build step. This does introduce a system dependency (for the `patch` command), unfortunately, but only when the Git fuzzer is being built.

**Comment by squeek502** [comment]
Sounds good, thanks!

**Pull request merged**
